# Generated by Django 4.1 on 2022-08-16 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Movie's categories", max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('born_date', models.DateField()),
                ('nationality', models.CharField(max_length=20)),
                ('biography', models.TextField(max_length=200)),
                ('spouse', models.CharField(max_length=40)),
                ('sons', models.CharField(help_text='Number of sons', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Movie's title", max_length=60, verbose_name='Movie')),
                ('synopsis', models.TextField(help_text="Movie's synopsis", max_length=200)),
                ('writer', models.CharField(help_text="Movie's writer", max_length=80, verbose_name='Writer')),
                ('stars', models.TextField(help_text="Movie's actors", max_length=100)),
                ('release_date', models.DateField()),
                ('category', models.ManyToManyField(to='catalog.category')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.director')),
            ],
        ),
    ]
